name: freejob-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # Har 30 minute chlega

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x scripts/run.sh

      - name: Run script
        env:
          WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          MAX_ITEMS: "10"
          SLEEP_BETWEEN_POSTS: "3"
        run: ./scripts/run.sh
